import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  glob,
  mkdir,
  readdir,
  readFile,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import {
  getAppScreenshot,
  screenshotFiles,
} from "../src/components/media/data/app-screenshots.ts";
import { getMessages } from "../src/i18n/messages.ts";

const check = process.argv.includes("--check");
const sources = [
  ...new Set([
    "/logo-small.webp",
    "/app-assets/cat-scottish-fold.webp",
    ...getMessages("ko").friends.cards.map((card) => card.path),
    ...["ko", "en"].flatMap((locale) =>
      Object.keys(screenshotFiles).map(
        (key) => getAppScreenshot(locale, key).src,
      ),
    ),
  ]),
].sort();
const widths = [48, 96, 160, 240, 320, 480, 640, 960, 1280];
const hash = (bytes) =>
  createHash("sha256").update(bytes).digest("hex").slice(0, 12);
const appAssets = [];
for await (const filename of glob("public/app-assets/**/*")) {
  if (/\.(png|jpe?g|webp|svg|gif)$/i.test(filename)) {
    appAssets.push(`/${filename.slice("public/".length)}`);
  }
}
assert.deepEqual(
  appAssets.sort(),
  sources.filter((src) => src.startsWith("/app-assets/")),
  "App assets must match the screenshot/friend catalogs; remove unused images.",
);
if (check) {
  const { responsiveImages } = await import(
    "../src/components/media/data/responsive-images.ts"
  );
  assert.deepEqual(Object.keys(responsiveImages).sort(), sources);
  const expectedFiles = new Set(
    Object.values(responsiveImages).flatMap((image) =>
      image.variants.map((variant) => path.basename(variant.src)),
    ),
  );
  assert.deepEqual(
    (await readdir("public/responsive")).sort(),
    [...expectedFiles].sort(),
    "Responsive assets must match the manifest; run pnpm images:generate.",
  );
  for (const src of sources) {
    const image = responsiveImages[src];
    assert.equal(
      hash(await readFile(`public${src}`)),
      image.sourceHash,
      `${src}: source changed; run pnpm images:generate`,
    );
    assert.deepEqual(
      image.variants.map((variant) => variant.width),
      [
        ...new Set([
          ...widths.filter((value) => value < image.width),
          image.width,
        ]),
      ],
    );
    for (const variant of image.variants) {
      const bytes = await readFile(`public${variant.src}`);
      assert.ok(
        variant.src.endsWith(`-${hash(bytes)}.webp`),
        `${variant.src}: content hash`,
      );
      const metadata = await sharp(bytes).metadata();
      assert.equal(metadata.width, variant.width);
      assert.equal(metadata.height, variant.height);
      assert.ok(variant.width <= image.width && bytes.length <= 300 * 1024);
    }
  }
  console.log(`Checked static variants for ${sources.length} source images.`);
  process.exit(0);
}
const manifest = {};
await mkdir("public/responsive", { recursive: true });
for (const src of sources) {
  const input = await readFile(`public${src}`);
  const { width, height } = await sharp(input).metadata();
  assert.ok(width && height, `${src}: dimensions required`);
  const variants = [];
  for (const target of [
    ...new Set([...widths.filter((value) => value < width), width]),
  ]) {
    const { data, info } = await sharp(input)
      .resize({ width: target, withoutEnlargement: true })
      .webp({ quality: 82, effort: 6 })
      .toBuffer({ resolveWithObject: true });
    const url = `/responsive/${path.basename(src, path.extname(src))}-${target}-${hash(data)}.webp`;
    await writeFile(`public${url}`, data);
    variants.push({ width: info.width, height: info.height, src: url });
  }
  manifest[src] = { sourceHash: hash(input), width, height, variants };
}
const output = `// Generated by pnpm images:generate. Keep source images unchanged.\nexport const responsiveImages = ${JSON.stringify(manifest, null, 2)} as const;\n`;
const filename = "src/components/media/data/responsive-images.ts";
await writeFile(filename, output);
const currentFiles = new Set(
  Object.values(manifest).flatMap((image) =>
    image.variants.map((variant) => path.basename(variant.src)),
  ),
);
for (const filename of await readdir("public/responsive")) {
  if (filename.endsWith(".webp") && !currentFiles.has(filename)) {
    await rm(path.join("public/responsive", filename));
  }
}
console.log(
  `Generated responsive variants for ${sources.length} source images.`,
);
