// Generated by pnpm images:generate. Keep source images unchanged.
export const responsiveImages = {
  "/app-assets/cat-abyssinian.webp": {
    "sourceHash": "0865e0d98624",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-abyssinian-48-dd59ab7b6200.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-abyssinian-96-97d480b7810f.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-abyssinian-160-bf9d90ecc130.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-abyssinian-240-a6c1993974e4.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-abyssinian-320-2f3ef1e437c3.webp"
      }
    ]
  },
  "/app-assets/cat-black.webp": {
    "sourceHash": "5f924a8d5484",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-black-48-f1867108fbf2.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-black-96-d59ba656eb72.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-black-160-63a3b3abea39.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-black-240-845fc6cb2a2f.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-black-320-fbb73baadee3.webp"
      }
    ]
  },
  "/app-assets/cat-cream.webp": {
    "sourceHash": "d741d8d8f73e",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-cream-48-b5bce49f6395.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-cream-96-bce2b3aa3272.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-cream-160-3ba04d1aeb2e.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-cream-240-990f7576d6a6.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-cream-320-3a078e87ad6c.webp"
      }
    ]
  },
  "/app-assets/cat-default.webp": {
    "sourceHash": "983a3839b31f",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-default-48-2e40226c64d1.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-default-96-217b9c8f5b0f.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-default-160-0083f095cec9.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-default-240-aa5c6c147df7.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-default-320-2b32a6a2501c.webp"
      }
    ]
  },
  "/app-assets/cat-orange-tabby.webp": {
    "sourceHash": "4fd30b269d45",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-orange-tabby-48-7fbd4e8417fd.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-orange-tabby-96-00fb3eed5567.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-orange-tabby-160-1bd1fa8cb129.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-orange-tabby-240-bb4cee4741a3.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-orange-tabby-320-5b583e6dbddc.webp"
      }
    ]
  },
  "/app-assets/cat-russian-blue.webp": {
    "sourceHash": "3173ab9b2187",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-russian-blue-48-ea5d07805dee.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-russian-blue-96-181cbc75afd5.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-russian-blue-160-bb7c004fb06b.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-russian-blue-240-f9423ccd648f.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-russian-blue-320-c370a5166955.webp"
      }
    ]
  },
  "/app-assets/cat-scottish-fold.webp": {
    "sourceHash": "ac082f14bb0c",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-scottish-fold-48-d9e456f0ef7c.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-scottish-fold-96-02ac0ac42908.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-scottish-fold-160-d6497ec0363b.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-scottish-fold-240-d5b29366f50a.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-scottish-fold-320-ebc39ae49752.webp"
      }
    ]
  },
  "/app-assets/cat-shyam.webp": {
    "sourceHash": "3c182ccfbb69",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-shyam-48-7ea143a40da1.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-shyam-96-af6c1e9bcd63.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-shyam-160-5232ffbcc064.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-shyam-240-217167aa5444.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-shyam-320-26a7a84c7633.webp"
      }
    ]
  },
  "/app-assets/cat-tuxedo.webp": {
    "sourceHash": "5eb40e50459f",
    "width": 320,
    "height": 320,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/cat-tuxedo-48-02216f08ab94.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/cat-tuxedo-96-72a344cea520.webp"
      },
      {
        "width": 160,
        "height": 160,
        "src": "/responsive/cat-tuxedo-160-26f6560e0df8.webp"
      },
      {
        "width": 240,
        "height": 240,
        "src": "/responsive/cat-tuxedo-240-f6f63422f1bc.webp"
      },
      {
        "width": 320,
        "height": 320,
        "src": "/responsive/cat-tuxedo-320-f4326e47128e.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/app-icons.webp": {
    "sourceHash": "5efe95bc93cb",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/app-icons-48-a7d1ec58239d.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/app-icons-96-a9146f6d5c9b.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/app-icons-160-907c8d958464.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/app-icons-240-049219e1b329.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/app-icons-320-c5b2138461fc.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/app-icons-480-6e5dbb0ab84d.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/home-month.webp": {
    "sourceHash": "fb8758d108fb",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/home-month-48-ce1832e4bac4.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/home-month-96-41fd34ced052.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/home-month-160-c6952a712215.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/home-month-240-d71fd61f394a.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/home-month-320-1acd004ab291.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/home-month-480-4ee8296b6383.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/memo-detail.webp": {
    "sourceHash": "692d67aa41bb",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/memo-detail-48-acacd1ff1004.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/memo-detail-96-b18a88af230b.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/memo-detail-160-217f23b4c473.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/memo-detail-240-bade22532090.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/memo-detail-320-e2edfe76bddb.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/memo-detail-480-9972dda70ad5.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/reminder-settings.webp": {
    "sourceHash": "b42eb2c3857e",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/reminder-settings-48-d7e65d3f7219.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/reminder-settings-96-d9a0a1c6409b.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/reminder-settings-160-ecc7aef9dc4f.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/reminder-settings-240-136a6aa96219.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/reminder-settings-320-b51815b40551.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/reminder-settings-480-1e974a5e5e85.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/repeat-picker.webp": {
    "sourceHash": "9b2263f1d7c9",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/repeat-picker-48-4c5c110ca521.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/repeat-picker-96-2cf96ce55ec1.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/repeat-picker-160-fe9e60d13c1f.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/repeat-picker-240-9a24ca42eb95.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/repeat-picker-320-bd47defb271c.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/repeat-picker-480-78a5dd6e94ef.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/sent-nudges.webp": {
    "sourceHash": "702f75b78093",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/sent-nudges-48-50f874bb9903.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/sent-nudges-96-ebbbc0fdd706.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/sent-nudges-160-5feacbaf0845.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/sent-nudges-240-543b9828215f.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/sent-nudges-320-3bbfaf82cae0.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/sent-nudges-480-e9eae86a8764.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/suggestions.webp": {
    "sourceHash": "7a5575f41980",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/suggestions-48-fe172b1b464a.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/suggestions-96-553c36a5781b.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/suggestions-160-efbbd598ea97.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/suggestions-240-02981779d49d.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/suggestions-320-9fc881eb249b.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/suggestions-480-6e931fda1903.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/thanks-sheet.webp": {
    "sourceHash": "b2827f7c3721",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/thanks-sheet-48-8b8955301b63.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/thanks-sheet-96-037240d0492f.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/thanks-sheet-160-02f51a8a7f9e.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/thanks-sheet-240-e83a380e6e57.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/thanks-sheet-320-d2be6fbea732.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/thanks-sheet-480-af7eae2c9cf5.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/weather.webp": {
    "sourceHash": "077f5581ede2",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/weather-48-8ef687c656d9.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/weather-96-1462515b4557.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/weather-160-d13c3d1271a2.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/weather-240-65c18b2b1756.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/weather-320-afd6be987ed7.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/weather-480-7eae40c57688.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/widgets-small.webp": {
    "sourceHash": "5a1d02e1274c",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/widgets-small-48-c221aad990d4.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/widgets-small-96-4b62e615a828.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/widgets-small-160-0e89b000a052.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/widgets-small-240-f7ed6bcd7fb3.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/widgets-small-320-d3e8a779bcde.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/widgets-small-480-7e0b58abdb12.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/android/widgets.webp": {
    "sourceHash": "8271af85e78b",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/widgets-48-4be8eeac8c0c.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/widgets-96-226e01c5d4f3.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/widgets-160-7cd3fdb6a1de.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/widgets-240-261c3c90ae78.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/widgets-320-fdc76a5ce620.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/widgets-480-7a31d34cac46.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/add-todo-filled.webp": {
    "sourceHash": "a210c80d355d",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/add-todo-filled-48-5492f90d87ad.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/add-todo-filled-96-14fe0b3a1b21.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/add-todo-filled-160-f20ce3523b52.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/add-todo-filled-240-e52bc2db69bb.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/add-todo-filled-320-4af11c264db4.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/add-todo-filled-480-f5ca88a46e35.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/friend-feed.webp": {
    "sourceHash": "cda43c130728",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/friend-feed-48-9773789c9f4a.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/friend-feed-96-437c3ca4d002.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/friend-feed-160-43c39a6cdaa0.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/friend-feed-240-f7f330de52e4.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/friend-feed-320-7c8fd4ac9bd5.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/friend-feed-480-e7b7bcd896ec.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/home-dark.webp": {
    "sourceHash": "2c729e84db4d",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/home-dark-48-59996ecc8e59.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/home-dark-96-ec9197810730.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/home-dark-160-dad9faef18f7.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/home-dark-240-f863d93cc4aa.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/home-dark-320-d6936b93c629.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/home-dark-480-567fb61390ab.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/home-week.webp": {
    "sourceHash": "9fd14060655f",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/home-week-48-f3ab6d4b5239.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/home-week-96-8bb30b3c90bb.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/home-week-160-187dd016be20.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/home-week-240-74113d037706.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/home-week-320-3ab1e5a27912.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/home-week-480-479690ad8b8a.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/memo-list.webp": {
    "sourceHash": "92fdcbcfd682",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/memo-list-48-2492be89dc32.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/memo-list-96-4c6e6f289d96.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/memo-list-160-b4dfeae769f2.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/memo-list-240-3fd191cd7d3c.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/memo-list-320-25d6d8f69614.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/memo-list-480-6b061bc6e08f.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/notifications.webp": {
    "sourceHash": "9e15394abed5",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/notifications-48-3318749c3154.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/notifications-96-bfee7e7820fd.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/notifications-160-ae515211d7b3.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/notifications-240-82fc15b572df.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/notifications-320-6fdf2c3bc715.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/notifications-480-f7ba1619fec8.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/nudge-detail.webp": {
    "sourceHash": "d919767f1faa",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/nudge-detail-48-526c4e220191.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/nudge-detail-96-709b4a103761.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/nudge-detail-160-8c9026d5d1c5.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/nudge-detail-240-a52d36dae57c.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/nudge-detail-320-7e659d461e20.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/nudge-detail-480-4f621e0e3e45.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/profile-cats.webp": {
    "sourceHash": "41af6d5c18e0",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/profile-cats-48-b821fe8aa846.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/profile-cats-96-f4f065ca566a.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/profile-cats-160-b290133410d0.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/profile-cats-240-0791aa2a379b.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/profile-cats-320-710af6c287cf.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/profile-cats-480-11c35719bc1f.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/report-sample.webp": {
    "sourceHash": "db6154011983",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/report-sample-48-ed02367729b6.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/report-sample-96-ffa3b4622485.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/report-sample-160-6dda0f2eeec8.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/report-sample-240-e958346d6073.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/report-sample-320-6c5faa99858b.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/report-sample-480-4721c54b47de.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/todo-detail.webp": {
    "sourceHash": "3aaa066fc545",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/todo-detail-48-02ec98635f4e.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/todo-detail-96-38b4eb31cfa9.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/todo-detail-160-d8b2a0fd3989.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/todo-detail-240-465eb3e5dfee.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/todo-detail-320-099121fe7904.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/todo-detail-480-7ed819ecd8c6.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/weather.webp": {
    "sourceHash": "d16ce54c0c53",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/weather-48-156b74451730.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/weather-96-43c5d488eb0d.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/weather-160-a518cb69f747.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/weather-240-fec918a98a47.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/weather-320-cb1f25b514e0.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/weather-480-1ebade4909ca.webp"
      }
    ]
  },
  "/app-assets/screenshots/en/ios/widgets.webp": {
    "sourceHash": "fd06700342e9",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/widgets-48-67a644cfefdd.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/widgets-96-39816138cc27.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/widgets-160-e9cb0fa23ca4.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/widgets-240-48d0fc099a7d.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/widgets-320-a83b85f846ac.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/widgets-480-8b1e30ebb27f.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/app-icons.webp": {
    "sourceHash": "551d486dff27",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/app-icons-48-e6d957e151d8.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/app-icons-96-fd089b1e4bb6.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/app-icons-160-6f387cb99381.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/app-icons-240-a38cd2413a5b.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/app-icons-320-ee3526e94523.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/app-icons-480-c3b564436993.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/home-month.webp": {
    "sourceHash": "2ab26c22cc47",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/home-month-48-4657e22975df.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/home-month-96-56535ff7a600.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/home-month-160-5fba26d5ffc9.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/home-month-240-da64ebf48ad3.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/home-month-320-0f7abc2d5709.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/home-month-480-b65caf687ee4.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/memo-detail.webp": {
    "sourceHash": "79d8c6943017",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/memo-detail-48-81130d36f0ba.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/memo-detail-96-78d4ca3e041d.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/memo-detail-160-062a0f647342.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/memo-detail-240-6a67119d7fd6.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/memo-detail-320-3b0f3ba7b863.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/memo-detail-480-d78f1e231e18.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/reminder-settings.webp": {
    "sourceHash": "5413b09ebffb",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/reminder-settings-48-e8c127f09939.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/reminder-settings-96-4fb15a48411a.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/reminder-settings-160-6ad7181b011f.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/reminder-settings-240-8edfea216d02.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/reminder-settings-320-8c3fb150dc05.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/reminder-settings-480-423e00b042f4.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/repeat-picker.webp": {
    "sourceHash": "a42ee21b43bc",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/repeat-picker-48-0fca97189fef.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/repeat-picker-96-f27395ab85c4.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/repeat-picker-160-24053238c235.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/repeat-picker-240-80b0756d2d46.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/repeat-picker-320-723f6ea86f8c.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/repeat-picker-480-a96ddc0299a9.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/sent-nudges.webp": {
    "sourceHash": "b438a2adf79a",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/sent-nudges-48-9294e64bb908.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/sent-nudges-96-bfa0c8169090.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/sent-nudges-160-5d01eb324959.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/sent-nudges-240-d0474248cf10.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/sent-nudges-320-e763cb44a317.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/sent-nudges-480-455e872f9283.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/suggestions.webp": {
    "sourceHash": "67a9c29ac982",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/suggestions-48-bfe68ae70b8e.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/suggestions-96-5fbdff6c775a.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/suggestions-160-8a32c4f0d1df.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/suggestions-240-7091695434ac.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/suggestions-320-ae7e64d4b471.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/suggestions-480-4324f014301a.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/thanks-sheet.webp": {
    "sourceHash": "b3c8db38e1c4",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/thanks-sheet-48-eb78d074f975.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/thanks-sheet-96-f6c4a5132964.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/thanks-sheet-160-7a0958ae77b5.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/thanks-sheet-240-380b8b1932c9.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/thanks-sheet-320-4a8ecef49616.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/thanks-sheet-480-81efbe88a81a.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/weather.webp": {
    "sourceHash": "1469022440a7",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/weather-48-23a38f05fe37.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/weather-96-d99f86b919ed.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/weather-160-1efbe6041d15.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/weather-240-71b81478f382.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/weather-320-1a678a14d1ac.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/weather-480-ff2a2e22faa8.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/widgets-small.webp": {
    "sourceHash": "52c2038d9f2f",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/widgets-small-48-8da8801bea6a.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/widgets-small-96-a1c3b0609710.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/widgets-small-160-6bc31c8c9c33.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/widgets-small-240-4e2b9af663a2.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/widgets-small-320-fa6209cb25be.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/widgets-small-480-8318fd1175f7.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/android/widgets.webp": {
    "sourceHash": "c7696dda7aa6",
    "width": 480,
    "height": 1067,
    "variants": [
      {
        "width": 48,
        "height": 107,
        "src": "/responsive/widgets-48-499e89f6a2df.webp"
      },
      {
        "width": 96,
        "height": 213,
        "src": "/responsive/widgets-96-33ee8568a7fe.webp"
      },
      {
        "width": 160,
        "height": 356,
        "src": "/responsive/widgets-160-202bdd36aecc.webp"
      },
      {
        "width": 240,
        "height": 534,
        "src": "/responsive/widgets-240-8c87e0206288.webp"
      },
      {
        "width": 320,
        "height": 711,
        "src": "/responsive/widgets-320-dde2ea8986c5.webp"
      },
      {
        "width": 480,
        "height": 1067,
        "src": "/responsive/widgets-480-d4102a4ef556.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/add-todo-filled.webp": {
    "sourceHash": "a5b506be7e60",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/add-todo-filled-48-9a18c7bef907.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/add-todo-filled-96-4095f55ea216.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/add-todo-filled-160-04e48dbb257e.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/add-todo-filled-240-4ffcb103b42a.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/add-todo-filled-320-b7636377970b.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/add-todo-filled-480-a6b10564225f.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/friend-feed.webp": {
    "sourceHash": "8aab3247b272",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/friend-feed-48-d74f7c6a1d7e.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/friend-feed-96-3cc3a8610965.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/friend-feed-160-4d0b4601db56.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/friend-feed-240-2146df06484e.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/friend-feed-320-f26a7e82e2a4.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/friend-feed-480-da7583b473fb.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/home-dark.webp": {
    "sourceHash": "cde3878d5a1b",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/home-dark-48-f41140044cb6.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/home-dark-96-553ec6370b61.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/home-dark-160-a1ae91b7880c.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/home-dark-240-0d55f0d6ed93.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/home-dark-320-cd9ea344ac8e.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/home-dark-480-b0c5ad2f4dec.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/home-week.webp": {
    "sourceHash": "6d71c3414123",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/home-week-48-36be89af4267.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/home-week-96-6a581cb328c7.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/home-week-160-bff2cbbe1853.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/home-week-240-d8181af498fa.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/home-week-320-d1981148172b.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/home-week-480-b18f0eb28379.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/memo-list.webp": {
    "sourceHash": "e8aa60330ef9",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/memo-list-48-2da19062b8f3.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/memo-list-96-784cdcbb71b2.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/memo-list-160-b737a6e7ffc9.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/memo-list-240-c0650e09b20d.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/memo-list-320-8c68681e162a.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/memo-list-480-2828352801e6.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/notifications.webp": {
    "sourceHash": "db3f0a6952d0",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/notifications-48-dd4957e477d5.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/notifications-96-c6f5a871a0fb.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/notifications-160-275b44bf61e8.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/notifications-240-bc4730686405.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/notifications-320-fcfa6217385b.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/notifications-480-a67aa0e8c241.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/nudge-detail.webp": {
    "sourceHash": "d8abf8321bf8",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/nudge-detail-48-c8601636c893.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/nudge-detail-96-8c060a67d557.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/nudge-detail-160-cfe822b9486b.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/nudge-detail-240-7b82685151da.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/nudge-detail-320-d6f65383683e.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/nudge-detail-480-12a1b3ff0915.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/profile-cats.webp": {
    "sourceHash": "a2633e9794d7",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/profile-cats-48-2dfa0b5ed5e1.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/profile-cats-96-17f430977c47.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/profile-cats-160-a02bf530e5c7.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/profile-cats-240-ba45adefa512.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/profile-cats-320-90a4b2928ea4.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/profile-cats-480-c969792f2467.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/report-sample.webp": {
    "sourceHash": "9049c15b9bfd",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/report-sample-48-9b2af21b9f82.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/report-sample-96-69a0de8e2ae5.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/report-sample-160-2b5fd90d036a.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/report-sample-240-2f9285374ed3.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/report-sample-320-64ae04f11077.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/report-sample-480-4c260428b969.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/todo-detail.webp": {
    "sourceHash": "4a1ee13b2211",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/todo-detail-48-4e1266edceba.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/todo-detail-96-378ecf603d73.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/todo-detail-160-044b4b07fe88.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/todo-detail-240-2e19e7b53ba8.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/todo-detail-320-854ca033a33e.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/todo-detail-480-df37ce263a3b.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/weather.webp": {
    "sourceHash": "9c5a0eaa33ed",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/weather-48-101d00c04e6a.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/weather-96-9edcfdb4fe37.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/weather-160-8caa1b92387d.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/weather-240-483ec2cb46a2.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/weather-320-6a1cd871b9fb.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/weather-480-7621c65119f2.webp"
      }
    ]
  },
  "/app-assets/screenshots/ko/ios/widgets.webp": {
    "sourceHash": "82e04271fc84",
    "width": 480,
    "height": 1044,
    "variants": [
      {
        "width": 48,
        "height": 104,
        "src": "/responsive/widgets-48-a4caf734e775.webp"
      },
      {
        "width": 96,
        "height": 209,
        "src": "/responsive/widgets-96-f09de15ced65.webp"
      },
      {
        "width": 160,
        "height": 348,
        "src": "/responsive/widgets-160-a24c5533e319.webp"
      },
      {
        "width": 240,
        "height": 522,
        "src": "/responsive/widgets-240-57cc6b7e360b.webp"
      },
      {
        "width": 320,
        "height": 696,
        "src": "/responsive/widgets-320-fcedf77d0e23.webp"
      },
      {
        "width": 480,
        "height": 1044,
        "src": "/responsive/widgets-480-14b2a8387ddb.webp"
      }
    ]
  },
  "/logo-small.webp": {
    "sourceHash": "866056406e43",
    "width": 96,
    "height": 96,
    "variants": [
      {
        "width": 48,
        "height": 48,
        "src": "/responsive/logo-small-48-523ce33eb999.webp"
      },
      {
        "width": 96,
        "height": 96,
        "src": "/responsive/logo-small-96-60c82b188bee.webp"
      }
    ]
  }
} as const;
